# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Staticcheck
      uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2023.1.5"
        install-go: false

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.54

    - name: Run coverage
      run: go test -race -coverprofile=coverage.out -covermode=atomic

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3

    - name: Build server
      run: go build -o gophkeeper.server.out ./cmd/server/

    - name: Archive server artifact
      uses: actions/upload-artifact@v3
      with:
        name: gophkeeper-server
        path: gophkeeper.server.out

    - name: Build CLI
      run: go build -o gophkeeper.cli.out ./cmd/cli/

    - name: Archive CLI artifact
      uses: actions/upload-artifact@v3
      with:
        name: gophkeeper-cli
        path: gophkeeper.cli.out
